### ISSUE TITLE
LaTeX issues

### ISSUE THREAD

**Issue by KOLANICH** [Deep-Symmetry/crate-digger#2]
Here are some suggestions how to improve your LaTeX:
1. use XeLaTeX . It works with ttf and otf and gives better appearance.
2. `\usepackage{cleveref}` - automatic crossreferences with links.
3. `\usepackage{hyperxmp}` - embeds XMP metadata block
4. `\usepackage{smartref}` - refs with human-readable names
5. set your metadata with `\hypersetup`
6. use `\usepackage[pdfusetitle]{hyperref}` to make hyperref to use the title set with `\title`

**Comment by brunchboy** [comment]
Thank you for the suggestions. If I have a bunch of free time someday I will see if it is practical to install XeLaTex on my Mac and learn how to use it, and explore these.

What is an XMP metadata block, and why is it desirable?

Also, I appreciate your input. I had a very bad reaction to your other issues initially because they seemed very hostile and presumptuous to me, as if demanding changes of the way I organize my open-source work, which is something I put thousands of hours into as a gift to the world—and I would never have phrased things that way in a comment I was making on someone else’s work. Now that I am forcing myself to calm down, I understand that it was probably down to a fundamental difference in communication style, so I am grateful that you cared enough to make suggestions.

**Comment by KOLANICH** [comment]
>What is an XMP metadata block, and why is it desirable?

It is a piece of XML often embedded into Adobe file formats. Some apps rely on the native pdf metadata , some apps rely on XMP, so usually one wants to have metadata in both formats.

>I had a very bad reaction to your other issues initially because they seemed very hostile and presumptuous to me, as if demanding changes of the way I organize my open-source work, which is something I put thousands of hours into as a gift to the world—and I would never have phrased things that way in a comment I was making on someone else’s work.

I'm sorry, if I was rude, that definitely wasn't intended. In fact I haven't even noticed that something is wrong untill you have explicitly brought that up. Thank you.

**Comment by brunchboy** [comment]
No worries! I was not trying to say that you were rude, I simply misread the tone of your first issue and reacted defensively. You did not do anything wrong, it just took me some time to realize that we were communicating with different styles. So I wanted to apologize if my early responses seemed rude to you. Thanks for the additional information about XMP. You have given me many things to think about for improvements.

**Comment by brunchboy** [comment]
It turns out XeLaTeX was already available on my system, so it was just a matter of figuring out how to make the file work well with it as well as pdfLaTeX. I can’t change the configuration of `hyperref` to include `pdfusetitle` because evidently my document style is already using `hyperref`. However, it does seem to properly encode the title regardless.

It would have been nice to know about `cleverref` before writing all my cross-references, it would have saved me a lot of work, and I will try to remember it for the future, but it seems not worth going back to change everything now. And I can’t see anything that `smartref` would add that `cleverref` doesn’t already do better?

**Comment by KOLANICH** [comment]
>And I can’t see anything that smartref would add that cleverref doesn’t already do better?

Thanks for bringing my attention to that. In fact I don't remember. I have created that boilerplatre years ago iteratively.  I will try to remove that and observe the effect, but now I'm pretty busy.

**Comment by brunchboy** [comment]
I have moved away from LaTeX to an Antora documentation site written in AsciiDoc, with the help of my new [bytefield-svg](https://github.com/Deep-Symmetry/bytefield-svg) diagram generator.
